// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: analytics/v1/analytics.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Daily nutrition summary request
type GetDailyNutritionSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyNutritionSummaryRequest) Reset() {
	*x = GetDailyNutritionSummaryRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyNutritionSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyNutritionSummaryRequest) ProtoMessage() {}

func (x *GetDailyNutritionSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyNutritionSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDailyNutritionSummaryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetDailyNutritionSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDailyNutritionSummaryRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Daily nutrition summary response
type GetDailyNutritionSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *DailyNutritionSummary `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyNutritionSummaryResponse) Reset() {
	*x = GetDailyNutritionSummaryResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyNutritionSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyNutritionSummaryResponse) ProtoMessage() {}

func (x *GetDailyNutritionSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyNutritionSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetDailyNutritionSummaryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetDailyNutritionSummaryResponse) GetSummary() *DailyNutritionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// Weekly nutrition trends request
type GetWeeklyNutritionTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD format
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyNutritionTrendsRequest) Reset() {
	*x = GetWeeklyNutritionTrendsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyNutritionTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyNutritionTrendsRequest) ProtoMessage() {}

func (x *GetWeeklyNutritionTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyNutritionTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetWeeklyNutritionTrendsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeeklyNutritionTrendsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWeeklyNutritionTrendsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetWeeklyNutritionTrendsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Weekly nutrition trends response
type GetWeeklyNutritionTrendsResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	DailySummaries []*DailyNutritionSummary `protobuf:"bytes,1,rep,name=daily_summaries,json=dailySummaries,proto3" json:"daily_summaries,omitempty"`
	Trends         *NutritionTrends         `protobuf:"bytes,2,opt,name=trends,proto3" json:"trends,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWeeklyNutritionTrendsResponse) Reset() {
	*x = GetWeeklyNutritionTrendsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyNutritionTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyNutritionTrendsResponse) ProtoMessage() {}

func (x *GetWeeklyNutritionTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyNutritionTrendsResponse.ProtoReflect.Descriptor instead.
func (*GetWeeklyNutritionTrendsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeeklyNutritionTrendsResponse) GetDailySummaries() []*DailyNutritionSummary {
	if x != nil {
		return x.DailySummaries
	}
	return nil
}

func (x *GetWeeklyNutritionTrendsResponse) GetTrends() *NutritionTrends {
	if x != nil {
		return x.Trends
	}
	return nil
}

// Monthly nutrition insights request
type GetMonthlyNutritionInsightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          string                 `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`   // YYYY format
	Month         string                 `protobuf:"bytes,3,opt,name=month,proto3" json:"month,omitempty"` // MM format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyNutritionInsightsRequest) Reset() {
	*x = GetMonthlyNutritionInsightsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyNutritionInsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyNutritionInsightsRequest) ProtoMessage() {}

func (x *GetMonthlyNutritionInsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyNutritionInsightsRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyNutritionInsightsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetMonthlyNutritionInsightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMonthlyNutritionInsightsRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *GetMonthlyNutritionInsightsRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

// Monthly nutrition insights response
type GetMonthlyNutritionInsightsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Insights      *MonthlyNutritionInsights `protobuf:"bytes,1,opt,name=insights,proto3" json:"insights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyNutritionInsightsResponse) Reset() {
	*x = GetMonthlyNutritionInsightsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyNutritionInsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyNutritionInsightsResponse) ProtoMessage() {}

func (x *GetMonthlyNutritionInsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyNutritionInsightsResponse.ProtoReflect.Descriptor instead.
func (*GetMonthlyNutritionInsightsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetMonthlyNutritionInsightsResponse) GetInsights() *MonthlyNutritionInsights {
	if x != nil {
		return x.Insights
	}
	return nil
}

// Weight progress analysis request
type GetWeightProgressAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD format
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeightProgressAnalysisRequest) Reset() {
	*x = GetWeightProgressAnalysisRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeightProgressAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightProgressAnalysisRequest) ProtoMessage() {}

func (x *GetWeightProgressAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightProgressAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetWeightProgressAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetWeightProgressAnalysisRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWeightProgressAnalysisRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetWeightProgressAnalysisRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Weight progress analysis response
type GetWeightProgressAnalysisResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Analysis      *WeightProgressAnalysis `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeightProgressAnalysisResponse) Reset() {
	*x = GetWeightProgressAnalysisResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeightProgressAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightProgressAnalysisResponse) ProtoMessage() {}

func (x *GetWeightProgressAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightProgressAnalysisResponse.ProtoReflect.Descriptor instead.
func (*GetWeightProgressAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetWeightProgressAnalysisResponse) GetAnalysis() *WeightProgressAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// Calorie balance analysis request
type GetCalorieBalanceAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD format
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalorieBalanceAnalysisRequest) Reset() {
	*x = GetCalorieBalanceAnalysisRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalorieBalanceAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalorieBalanceAnalysisRequest) ProtoMessage() {}

func (x *GetCalorieBalanceAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalorieBalanceAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetCalorieBalanceAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetCalorieBalanceAnalysisRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCalorieBalanceAnalysisRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetCalorieBalanceAnalysisRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Calorie balance analysis response
type GetCalorieBalanceAnalysisResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Analysis      *CalorieBalanceAnalysis `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalorieBalanceAnalysisResponse) Reset() {
	*x = GetCalorieBalanceAnalysisResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalorieBalanceAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalorieBalanceAnalysisResponse) ProtoMessage() {}

func (x *GetCalorieBalanceAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalorieBalanceAnalysisResponse.ProtoReflect.Descriptor instead.
func (*GetCalorieBalanceAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetCalorieBalanceAnalysisResponse) GetAnalysis() *CalorieBalanceAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// Daily nutrition summary
type DailyNutritionSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CaloriesIntake  int32                  `protobuf:"varint,2,opt,name=calories_intake,json=caloriesIntake,proto3" json:"calories_intake,omitempty"`
	CaloriesBurned  int32                  `protobuf:"varint,3,opt,name=calories_burned,json=caloriesBurned,proto3" json:"calories_burned,omitempty"`
	CaloriesBalance int32                  `protobuf:"varint,4,opt,name=calories_balance,json=caloriesBalance,proto3" json:"calories_balance,omitempty"`
	Protein         int32                  `protobuf:"varint,5,opt,name=protein,proto3" json:"protein,omitempty"`
	Carbohydrate    int32                  `protobuf:"varint,6,opt,name=carbohydrate,proto3" json:"carbohydrate,omitempty"`
	Fat             int32                  `protobuf:"varint,7,opt,name=fat,proto3" json:"fat,omitempty"`
	Fiber           int32                  `protobuf:"varint,8,opt,name=fiber,proto3" json:"fiber,omitempty"`
	Sugar           int32                  `protobuf:"varint,9,opt,name=sugar,proto3" json:"sugar,omitempty"`
	Sodium          int32                  `protobuf:"varint,10,opt,name=sodium,proto3" json:"sodium,omitempty"`
	Meals           []*MealSummary         `protobuf:"bytes,11,rep,name=meals,proto3" json:"meals,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyNutritionSummary) Reset() {
	*x = DailyNutritionSummary{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyNutritionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyNutritionSummary) ProtoMessage() {}

func (x *DailyNutritionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyNutritionSummary.ProtoReflect.Descriptor instead.
func (*DailyNutritionSummary) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *DailyNutritionSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyNutritionSummary) GetCaloriesIntake() int32 {
	if x != nil {
		return x.CaloriesIntake
	}
	return 0
}

func (x *DailyNutritionSummary) GetCaloriesBurned() int32 {
	if x != nil {
		return x.CaloriesBurned
	}
	return 0
}

func (x *DailyNutritionSummary) GetCaloriesBalance() int32 {
	if x != nil {
		return x.CaloriesBalance
	}
	return 0
}

func (x *DailyNutritionSummary) GetProtein() int32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *DailyNutritionSummary) GetCarbohydrate() int32 {
	if x != nil {
		return x.Carbohydrate
	}
	return 0
}

func (x *DailyNutritionSummary) GetFat() int32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *DailyNutritionSummary) GetFiber() int32 {
	if x != nil {
		return x.Fiber
	}
	return 0
}

func (x *DailyNutritionSummary) GetSugar() int32 {
	if x != nil {
		return x.Sugar
	}
	return 0
}

func (x *DailyNutritionSummary) GetSodium() int32 {
	if x != nil {
		return x.Sodium
	}
	return 0
}

func (x *DailyNutritionSummary) GetMeals() []*MealSummary {
	if x != nil {
		return x.Meals
	}
	return nil
}

// Meal summary
type MealSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MealType      string                 `protobuf:"bytes,1,opt,name=meal_type,json=mealType,proto3" json:"meal_type,omitempty"` // breakfast, lunch, dinner, snack
	Calories      int32                  `protobuf:"varint,2,opt,name=calories,proto3" json:"calories,omitempty"`
	Protein       int32                  `protobuf:"varint,3,opt,name=protein,proto3" json:"protein,omitempty"`
	Carbohydrate  int32                  `protobuf:"varint,4,opt,name=carbohydrate,proto3" json:"carbohydrate,omitempty"`
	Fat           int32                  `protobuf:"varint,5,opt,name=fat,proto3" json:"fat,omitempty"`
	FoodItems     []string               `protobuf:"bytes,6,rep,name=food_items,json=foodItems,proto3" json:"food_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealSummary) Reset() {
	*x = MealSummary{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealSummary) ProtoMessage() {}

func (x *MealSummary) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealSummary.ProtoReflect.Descriptor instead.
func (*MealSummary) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *MealSummary) GetMealType() string {
	if x != nil {
		return x.MealType
	}
	return ""
}

func (x *MealSummary) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *MealSummary) GetProtein() int32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *MealSummary) GetCarbohydrate() int32 {
	if x != nil {
		return x.Carbohydrate
	}
	return 0
}

func (x *MealSummary) GetFat() int32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *MealSummary) GetFoodItems() []string {
	if x != nil {
		return x.FoodItems
	}
	return nil
}

// Nutrition trends
type NutritionTrends struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CaloriesAvg       float64                `protobuf:"fixed64,1,opt,name=calories_avg,json=caloriesAvg,proto3" json:"calories_avg,omitempty"`
	ProteinAvg        float64                `protobuf:"fixed64,2,opt,name=protein_avg,json=proteinAvg,proto3" json:"protein_avg,omitempty"`
	CarbohydrateAvg   float64                `protobuf:"fixed64,3,opt,name=carbohydrate_avg,json=carbohydrateAvg,proto3" json:"carbohydrate_avg,omitempty"`
	FatAvg            float64                `protobuf:"fixed64,4,opt,name=fat_avg,json=fatAvg,proto3" json:"fat_avg,omitempty"`
	CaloriesTrend     float64                `protobuf:"fixed64,5,opt,name=calories_trend,json=caloriesTrend,proto3" json:"calories_trend,omitempty"` // percentage change
	ProteinTrend      float64                `protobuf:"fixed64,6,opt,name=protein_trend,json=proteinTrend,proto3" json:"protein_trend,omitempty"`
	CarbohydrateTrend float64                `protobuf:"fixed64,7,opt,name=carbohydrate_trend,json=carbohydrateTrend,proto3" json:"carbohydrate_trend,omitempty"`
	FatTrend          float64                `protobuf:"fixed64,8,opt,name=fat_trend,json=fatTrend,proto3" json:"fat_trend,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NutritionTrends) Reset() {
	*x = NutritionTrends{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionTrends) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionTrends) ProtoMessage() {}

func (x *NutritionTrends) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionTrends.ProtoReflect.Descriptor instead.
func (*NutritionTrends) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *NutritionTrends) GetCaloriesAvg() float64 {
	if x != nil {
		return x.CaloriesAvg
	}
	return 0
}

func (x *NutritionTrends) GetProteinAvg() float64 {
	if x != nil {
		return x.ProteinAvg
	}
	return 0
}

func (x *NutritionTrends) GetCarbohydrateAvg() float64 {
	if x != nil {
		return x.CarbohydrateAvg
	}
	return 0
}

func (x *NutritionTrends) GetFatAvg() float64 {
	if x != nil {
		return x.FatAvg
	}
	return 0
}

func (x *NutritionTrends) GetCaloriesTrend() float64 {
	if x != nil {
		return x.CaloriesTrend
	}
	return 0
}

func (x *NutritionTrends) GetProteinTrend() float64 {
	if x != nil {
		return x.ProteinTrend
	}
	return 0
}

func (x *NutritionTrends) GetCarbohydrateTrend() float64 {
	if x != nil {
		return x.CarbohydrateTrend
	}
	return 0
}

func (x *NutritionTrends) GetFatTrend() float64 {
	if x != nil {
		return x.FatTrend
	}
	return 0
}

// Monthly nutrition insights
type MonthlyNutritionInsights struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Year                 string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalCalories        int32                  `protobuf:"varint,3,opt,name=total_calories,json=totalCalories,proto3" json:"total_calories,omitempty"`
	AvgDailyCalories     int32                  `protobuf:"varint,4,opt,name=avg_daily_calories,json=avgDailyCalories,proto3" json:"avg_daily_calories,omitempty"`
	TotalProtein         int32                  `protobuf:"varint,5,opt,name=total_protein,json=totalProtein,proto3" json:"total_protein,omitempty"`
	AvgDailyProtein      int32                  `protobuf:"varint,6,opt,name=avg_daily_protein,json=avgDailyProtein,proto3" json:"avg_daily_protein,omitempty"`
	TotalCarbohydrate    int32                  `protobuf:"varint,7,opt,name=total_carbohydrate,json=totalCarbohydrate,proto3" json:"total_carbohydrate,omitempty"`
	AvgDailyCarbohydrate int32                  `protobuf:"varint,8,opt,name=avg_daily_carbohydrate,json=avgDailyCarbohydrate,proto3" json:"avg_daily_carbohydrate,omitempty"`
	TotalFat             int32                  `protobuf:"varint,9,opt,name=total_fat,json=totalFat,proto3" json:"total_fat,omitempty"`
	AvgDailyFat          int32                  `protobuf:"varint,10,opt,name=avg_daily_fat,json=avgDailyFat,proto3" json:"avg_daily_fat,omitempty"`
	TopFoods             []string               `protobuf:"bytes,11,rep,name=top_foods,json=topFoods,proto3" json:"top_foods,omitempty"`
	Recommendations      []string               `protobuf:"bytes,12,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MonthlyNutritionInsights) Reset() {
	*x = MonthlyNutritionInsights{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyNutritionInsights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyNutritionInsights) ProtoMessage() {}

func (x *MonthlyNutritionInsights) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyNutritionInsights.ProtoReflect.Descriptor instead.
func (*MonthlyNutritionInsights) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *MonthlyNutritionInsights) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *MonthlyNutritionInsights) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyNutritionInsights) GetTotalCalories() int32 {
	if x != nil {
		return x.TotalCalories
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetAvgDailyCalories() int32 {
	if x != nil {
		return x.AvgDailyCalories
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetTotalProtein() int32 {
	if x != nil {
		return x.TotalProtein
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetAvgDailyProtein() int32 {
	if x != nil {
		return x.AvgDailyProtein
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetTotalCarbohydrate() int32 {
	if x != nil {
		return x.TotalCarbohydrate
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetAvgDailyCarbohydrate() int32 {
	if x != nil {
		return x.AvgDailyCarbohydrate
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetTotalFat() int32 {
	if x != nil {
		return x.TotalFat
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetAvgDailyFat() int32 {
	if x != nil {
		return x.AvgDailyFat
	}
	return 0
}

func (x *MonthlyNutritionInsights) GetTopFoods() []string {
	if x != nil {
		return x.TopFoods
	}
	return nil
}

func (x *MonthlyNutritionInsights) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// Weight progress analysis
type WeightProgressAnalysis struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	StartDate              string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate                string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	StartWeight            float64                `protobuf:"fixed64,3,opt,name=start_weight,json=startWeight,proto3" json:"start_weight,omitempty"`
	EndWeight              float64                `protobuf:"fixed64,4,opt,name=end_weight,json=endWeight,proto3" json:"end_weight,omitempty"`
	WeightChange           float64                `protobuf:"fixed64,5,opt,name=weight_change,json=weightChange,proto3" json:"weight_change,omitempty"`
	WeightChangePercentage float64                `protobuf:"fixed64,6,opt,name=weight_change_percentage,json=weightChangePercentage,proto3" json:"weight_change_percentage,omitempty"`
	AvgWeeklyChange        float64                `protobuf:"fixed64,7,opt,name=avg_weekly_change,json=avgWeeklyChange,proto3" json:"avg_weekly_change,omitempty"`
	DataPoints             []*WeightDataPoint     `protobuf:"bytes,8,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Trend                  string                 `protobuf:"bytes,9,opt,name=trend,proto3" json:"trend,omitempty"` // increasing, decreasing, stable
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WeightProgressAnalysis) Reset() {
	*x = WeightProgressAnalysis{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightProgressAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightProgressAnalysis) ProtoMessage() {}

func (x *WeightProgressAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightProgressAnalysis.ProtoReflect.Descriptor instead.
func (*WeightProgressAnalysis) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *WeightProgressAnalysis) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *WeightProgressAnalysis) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *WeightProgressAnalysis) GetStartWeight() float64 {
	if x != nil {
		return x.StartWeight
	}
	return 0
}

func (x *WeightProgressAnalysis) GetEndWeight() float64 {
	if x != nil {
		return x.EndWeight
	}
	return 0
}

func (x *WeightProgressAnalysis) GetWeightChange() float64 {
	if x != nil {
		return x.WeightChange
	}
	return 0
}

func (x *WeightProgressAnalysis) GetWeightChangePercentage() float64 {
	if x != nil {
		return x.WeightChangePercentage
	}
	return 0
}

func (x *WeightProgressAnalysis) GetAvgWeeklyChange() float64 {
	if x != nil {
		return x.AvgWeeklyChange
	}
	return 0
}

func (x *WeightProgressAnalysis) GetDataPoints() []*WeightDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *WeightProgressAnalysis) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

// Weight data point
type WeightDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightDataPoint) Reset() {
	*x = WeightDataPoint{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightDataPoint) ProtoMessage() {}

func (x *WeightDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightDataPoint.ProtoReflect.Descriptor instead.
func (*WeightDataPoint) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *WeightDataPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WeightDataPoint) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// Calorie balance analysis
type CalorieBalanceAnalysis struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StartDate           string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate             string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TotalCaloriesIntake int32                  `protobuf:"varint,3,opt,name=total_calories_intake,json=totalCaloriesIntake,proto3" json:"total_calories_intake,omitempty"`
	TotalCaloriesBurned int32                  `protobuf:"varint,4,opt,name=total_calories_burned,json=totalCaloriesBurned,proto3" json:"total_calories_burned,omitempty"`
	TotalCalorieBalance int32                  `protobuf:"varint,5,opt,name=total_calorie_balance,json=totalCalorieBalance,proto3" json:"total_calorie_balance,omitempty"`
	AvgDailyBalance     float64                `protobuf:"fixed64,6,opt,name=avg_daily_balance,json=avgDailyBalance,proto3" json:"avg_daily_balance,omitempty"`
	DaysInDeficit       int32                  `protobuf:"varint,7,opt,name=days_in_deficit,json=daysInDeficit,proto3" json:"days_in_deficit,omitempty"`
	DaysInSurplus       int32                  `protobuf:"varint,8,opt,name=days_in_surplus,json=daysInSurplus,proto3" json:"days_in_surplus,omitempty"`
	DeficitPercentage   float64                `protobuf:"fixed64,9,opt,name=deficit_percentage,json=deficitPercentage,proto3" json:"deficit_percentage,omitempty"`
	DailyBalances       []*DailyBalance        `protobuf:"bytes,10,rep,name=daily_balances,json=dailyBalances,proto3" json:"daily_balances,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CalorieBalanceAnalysis) Reset() {
	*x = CalorieBalanceAnalysis{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalorieBalanceAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalorieBalanceAnalysis) ProtoMessage() {}

func (x *CalorieBalanceAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalorieBalanceAnalysis.ProtoReflect.Descriptor instead.
func (*CalorieBalanceAnalysis) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *CalorieBalanceAnalysis) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CalorieBalanceAnalysis) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CalorieBalanceAnalysis) GetTotalCaloriesIntake() int32 {
	if x != nil {
		return x.TotalCaloriesIntake
	}
	return 0
}

func (x *CalorieBalanceAnalysis) GetTotalCaloriesBurned() int32 {
	if x != nil {
		return x.TotalCaloriesBurned
	}
	return 0
}

func (x *CalorieBalanceAnalysis) GetTotalCalorieBalance() int32 {
	if x != nil {
		return x.TotalCalorieBalance
	}
	return 0
}

func (x *CalorieBalanceAnalysis) GetAvgDailyBalance() float64 {
	if x != nil {
		return x.AvgDailyBalance
	}
	return 0
}

func (x *CalorieBalanceAnalysis) GetDaysInDeficit() int32 {
	if x != nil {
		return x.DaysInDeficit
	}
	return 0
}

func (x *CalorieBalanceAnalysis) GetDaysInSurplus() int32 {
	if x != nil {
		return x.DaysInSurplus
	}
	return 0
}

func (x *CalorieBalanceAnalysis) GetDeficitPercentage() float64 {
	if x != nil {
		return x.DeficitPercentage
	}
	return 0
}

func (x *CalorieBalanceAnalysis) GetDailyBalances() []*DailyBalance {
	if x != nil {
		return x.DailyBalances
	}
	return nil
}

// Daily balance
type DailyBalance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Date           string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CaloriesIntake int32                  `protobuf:"varint,2,opt,name=calories_intake,json=caloriesIntake,proto3" json:"calories_intake,omitempty"`
	CaloriesBurned int32                  `protobuf:"varint,3,opt,name=calories_burned,json=caloriesBurned,proto3" json:"calories_burned,omitempty"`
	Balance        int32                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DailyBalance) Reset() {
	*x = DailyBalance{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyBalance) ProtoMessage() {}

func (x *DailyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyBalance.ProtoReflect.Descriptor instead.
func (*DailyBalance) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *DailyBalance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyBalance) GetCaloriesIntake() int32 {
	if x != nil {
		return x.CaloriesIntake
	}
	return 0
}

func (x *DailyBalance) GetCaloriesBurned() int32 {
	if x != nil {
		return x.CaloriesBurned
	}
	return 0
}

func (x *DailyBalance) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\fanalytics.v1\"N\n" +
	"\x1fGetDailyNutritionSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"a\n" +
	" GetDailyNutritionSummaryResponse\x12=\n" +
	"\asummary\x18\x01 \x01(\v2#.analytics.v1.DailyNutritionSummaryR\asummary\"t\n" +
	"\x1fGetWeeklyNutritionTrendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xa7\x01\n" +
	" GetWeeklyNutritionTrendsResponse\x12L\n" +
	"\x0fdaily_summaries\x18\x01 \x03(\v2#.analytics.v1.DailyNutritionSummaryR\x0edailySummaries\x125\n" +
	"\x06trends\x18\x02 \x01(\v2\x1d.analytics.v1.NutritionTrendsR\x06trends\"g\n" +
	"\"GetMonthlyNutritionInsightsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\tR\x05month\"i\n" +
	"#GetMonthlyNutritionInsightsResponse\x12B\n" +
	"\binsights\x18\x01 \x01(\v2&.analytics.v1.MonthlyNutritionInsightsR\binsights\"u\n" +
	" GetWeightProgressAnalysisRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"e\n" +
	"!GetWeightProgressAnalysisResponse\x12@\n" +
	"\banalysis\x18\x01 \x01(\v2$.analytics.v1.WeightProgressAnalysisR\banalysis\"u\n" +
	" GetCalorieBalanceAnalysisRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"e\n" +
	"!GetCalorieBalanceAnalysisResponse\x12@\n" +
	"\banalysis\x18\x01 \x01(\v2$.analytics.v1.CalorieBalanceAnalysisR\banalysis\"\xed\x02\n" +
	"\x15DailyNutritionSummary\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12'\n" +
	"\x0fcalories_intake\x18\x02 \x01(\x05R\x0ecaloriesIntake\x12'\n" +
	"\x0fcalories_burned\x18\x03 \x01(\x05R\x0ecaloriesBurned\x12)\n" +
	"\x10calories_balance\x18\x04 \x01(\x05R\x0fcaloriesBalance\x12\x18\n" +
	"\aprotein\x18\x05 \x01(\x05R\aprotein\x12\"\n" +
	"\fcarbohydrate\x18\x06 \x01(\x05R\fcarbohydrate\x12\x10\n" +
	"\x03fat\x18\a \x01(\x05R\x03fat\x12\x14\n" +
	"\x05fiber\x18\b \x01(\x05R\x05fiber\x12\x14\n" +
	"\x05sugar\x18\t \x01(\x05R\x05sugar\x12\x16\n" +
	"\x06sodium\x18\n" +
	" \x01(\x05R\x06sodium\x12/\n" +
	"\x05meals\x18\v \x03(\v2\x19.analytics.v1.MealSummaryR\x05meals\"\xb5\x01\n" +
	"\vMealSummary\x12\x1b\n" +
	"\tmeal_type\x18\x01 \x01(\tR\bmealType\x12\x1a\n" +
	"\bcalories\x18\x02 \x01(\x05R\bcalories\x12\x18\n" +
	"\aprotein\x18\x03 \x01(\x05R\aprotein\x12\"\n" +
	"\fcarbohydrate\x18\x04 \x01(\x05R\fcarbohydrate\x12\x10\n" +
	"\x03fat\x18\x05 \x01(\x05R\x03fat\x12\x1d\n" +
	"\n" +
	"food_items\x18\x06 \x03(\tR\tfoodItems\"\xb1\x02\n" +
	"\x0fNutritionTrends\x12!\n" +
	"\fcalories_avg\x18\x01 \x01(\x01R\vcaloriesAvg\x12\x1f\n" +
	"\vprotein_avg\x18\x02 \x01(\x01R\n" +
	"proteinAvg\x12)\n" +
	"\x10carbohydrate_avg\x18\x03 \x01(\x01R\x0fcarbohydrateAvg\x12\x17\n" +
	"\afat_avg\x18\x04 \x01(\x01R\x06fatAvg\x12%\n" +
	"\x0ecalories_trend\x18\x05 \x01(\x01R\rcaloriesTrend\x12#\n" +
	"\rprotein_trend\x18\x06 \x01(\x01R\fproteinTrend\x12-\n" +
	"\x12carbohydrate_trend\x18\a \x01(\x01R\x11carbohydrateTrend\x12\x1b\n" +
	"\tfat_trend\x18\b \x01(\x01R\bfatTrend\"\xd7\x03\n" +
	"\x18MonthlyNutritionInsights\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12%\n" +
	"\x0etotal_calories\x18\x03 \x01(\x05R\rtotalCalories\x12,\n" +
	"\x12avg_daily_calories\x18\x04 \x01(\x05R\x10avgDailyCalories\x12#\n" +
	"\rtotal_protein\x18\x05 \x01(\x05R\ftotalProtein\x12*\n" +
	"\x11avg_daily_protein\x18\x06 \x01(\x05R\x0favgDailyProtein\x12-\n" +
	"\x12total_carbohydrate\x18\a \x01(\x05R\x11totalCarbohydrate\x124\n" +
	"\x16avg_daily_carbohydrate\x18\b \x01(\x05R\x14avgDailyCarbohydrate\x12\x1b\n" +
	"\ttotal_fat\x18\t \x01(\x05R\btotalFat\x12\"\n" +
	"\ravg_daily_fat\x18\n" +
	" \x01(\x05R\vavgDailyFat\x12\x1b\n" +
	"\ttop_foods\x18\v \x03(\tR\btopFoods\x12(\n" +
	"\x0frecommendations\x18\f \x03(\tR\x0frecommendations\"\xf5\x02\n" +
	"\x16WeightProgressAnalysis\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12!\n" +
	"\fstart_weight\x18\x03 \x01(\x01R\vstartWeight\x12\x1d\n" +
	"\n" +
	"end_weight\x18\x04 \x01(\x01R\tendWeight\x12#\n" +
	"\rweight_change\x18\x05 \x01(\x01R\fweightChange\x128\n" +
	"\x18weight_change_percentage\x18\x06 \x01(\x01R\x16weightChangePercentage\x12*\n" +
	"\x11avg_weekly_change\x18\a \x01(\x01R\x0favgWeeklyChange\x12>\n" +
	"\vdata_points\x18\b \x03(\v2\x1d.analytics.v1.WeightDataPointR\n" +
	"dataPoints\x12\x14\n" +
	"\x05trend\x18\t \x01(\tR\x05trend\"=\n" +
	"\x0fWeightDataPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"\xdc\x03\n" +
	"\x16CalorieBalanceAnalysis\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x122\n" +
	"\x15total_calories_intake\x18\x03 \x01(\x05R\x13totalCaloriesIntake\x122\n" +
	"\x15total_calories_burned\x18\x04 \x01(\x05R\x13totalCaloriesBurned\x122\n" +
	"\x15total_calorie_balance\x18\x05 \x01(\x05R\x13totalCalorieBalance\x12*\n" +
	"\x11avg_daily_balance\x18\x06 \x01(\x01R\x0favgDailyBalance\x12&\n" +
	"\x0fdays_in_deficit\x18\a \x01(\x05R\rdaysInDeficit\x12&\n" +
	"\x0fdays_in_surplus\x18\b \x01(\x05R\rdaysInSurplus\x12-\n" +
	"\x12deficit_percentage\x18\t \x01(\x01R\x11deficitPercentage\x12A\n" +
	"\x0edaily_balances\x18\n" +
	" \x03(\v2\x1a.analytics.v1.DailyBalanceR\rdailyBalances\"\x8e\x01\n" +
	"\fDailyBalance\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12'\n" +
	"\x0fcalories_intake\x18\x02 \x01(\x05R\x0ecaloriesIntake\x12'\n" +
	"\x0fcalories_burned\x18\x03 \x01(\x05R\x0ecaloriesBurned\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x05R\abalance2\x89\x05\n" +
	"\x10AnalyticsService\x12y\n" +
	"\x18GetDailyNutritionSummary\x12-.analytics.v1.GetDailyNutritionSummaryRequest\x1a..analytics.v1.GetDailyNutritionSummaryResponse\x12y\n" +
	"\x18GetWeeklyNutritionTrends\x12-.analytics.v1.GetWeeklyNutritionTrendsRequest\x1a..analytics.v1.GetWeeklyNutritionTrendsResponse\x12\x82\x01\n" +
	"\x1bGetMonthlyNutritionInsights\x120.analytics.v1.GetMonthlyNutritionInsightsRequest\x1a1.analytics.v1.GetMonthlyNutritionInsightsResponse\x12|\n" +
	"\x19GetWeightProgressAnalysis\x12..analytics.v1.GetWeightProgressAnalysisRequest\x1a/.analytics.v1.GetWeightProgressAnalysisResponse\x12|\n" +
	"\x19GetCalorieBalanceAnalysis\x12..analytics.v1.GetCalorieBalanceAnalysisRequest\x1a/.analytics.v1.GetCalorieBalanceAnalysisResponseB>Z<github.com/HirotakaUchishiba/calomeal_mvp/proto/analytics/v1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(*GetDailyNutritionSummaryRequest)(nil),     // 0: analytics.v1.GetDailyNutritionSummaryRequest
	(*GetDailyNutritionSummaryResponse)(nil),    // 1: analytics.v1.GetDailyNutritionSummaryResponse
	(*GetWeeklyNutritionTrendsRequest)(nil),     // 2: analytics.v1.GetWeeklyNutritionTrendsRequest
	(*GetWeeklyNutritionTrendsResponse)(nil),    // 3: analytics.v1.GetWeeklyNutritionTrendsResponse
	(*GetMonthlyNutritionInsightsRequest)(nil),  // 4: analytics.v1.GetMonthlyNutritionInsightsRequest
	(*GetMonthlyNutritionInsightsResponse)(nil), // 5: analytics.v1.GetMonthlyNutritionInsightsResponse
	(*GetWeightProgressAnalysisRequest)(nil),    // 6: analytics.v1.GetWeightProgressAnalysisRequest
	(*GetWeightProgressAnalysisResponse)(nil),   // 7: analytics.v1.GetWeightProgressAnalysisResponse
	(*GetCalorieBalanceAnalysisRequest)(nil),    // 8: analytics.v1.GetCalorieBalanceAnalysisRequest
	(*GetCalorieBalanceAnalysisResponse)(nil),   // 9: analytics.v1.GetCalorieBalanceAnalysisResponse
	(*DailyNutritionSummary)(nil),               // 10: analytics.v1.DailyNutritionSummary
	(*MealSummary)(nil),                         // 11: analytics.v1.MealSummary
	(*NutritionTrends)(nil),                     // 12: analytics.v1.NutritionTrends
	(*MonthlyNutritionInsights)(nil),            // 13: analytics.v1.MonthlyNutritionInsights
	(*WeightProgressAnalysis)(nil),              // 14: analytics.v1.WeightProgressAnalysis
	(*WeightDataPoint)(nil),                     // 15: analytics.v1.WeightDataPoint
	(*CalorieBalanceAnalysis)(nil),              // 16: analytics.v1.CalorieBalanceAnalysis
	(*DailyBalance)(nil),                        // 17: analytics.v1.DailyBalance
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	10, // 0: analytics.v1.GetDailyNutritionSummaryResponse.summary:type_name -> analytics.v1.DailyNutritionSummary
	10, // 1: analytics.v1.GetWeeklyNutritionTrendsResponse.daily_summaries:type_name -> analytics.v1.DailyNutritionSummary
	12, // 2: analytics.v1.GetWeeklyNutritionTrendsResponse.trends:type_name -> analytics.v1.NutritionTrends
	13, // 3: analytics.v1.GetMonthlyNutritionInsightsResponse.insights:type_name -> analytics.v1.MonthlyNutritionInsights
	14, // 4: analytics.v1.GetWeightProgressAnalysisResponse.analysis:type_name -> analytics.v1.WeightProgressAnalysis
	16, // 5: analytics.v1.GetCalorieBalanceAnalysisResponse.analysis:type_name -> analytics.v1.CalorieBalanceAnalysis
	11, // 6: analytics.v1.DailyNutritionSummary.meals:type_name -> analytics.v1.MealSummary
	15, // 7: analytics.v1.WeightProgressAnalysis.data_points:type_name -> analytics.v1.WeightDataPoint
	17, // 8: analytics.v1.CalorieBalanceAnalysis.daily_balances:type_name -> analytics.v1.DailyBalance
	0,  // 9: analytics.v1.AnalyticsService.GetDailyNutritionSummary:input_type -> analytics.v1.GetDailyNutritionSummaryRequest
	2,  // 10: analytics.v1.AnalyticsService.GetWeeklyNutritionTrends:input_type -> analytics.v1.GetWeeklyNutritionTrendsRequest
	4,  // 11: analytics.v1.AnalyticsService.GetMonthlyNutritionInsights:input_type -> analytics.v1.GetMonthlyNutritionInsightsRequest
	6,  // 12: analytics.v1.AnalyticsService.GetWeightProgressAnalysis:input_type -> analytics.v1.GetWeightProgressAnalysisRequest
	8,  // 13: analytics.v1.AnalyticsService.GetCalorieBalanceAnalysis:input_type -> analytics.v1.GetCalorieBalanceAnalysisRequest
	1,  // 14: analytics.v1.AnalyticsService.GetDailyNutritionSummary:output_type -> analytics.v1.GetDailyNutritionSummaryResponse
	3,  // 15: analytics.v1.AnalyticsService.GetWeeklyNutritionTrends:output_type -> analytics.v1.GetWeeklyNutritionTrendsResponse
	5,  // 16: analytics.v1.AnalyticsService.GetMonthlyNutritionInsights:output_type -> analytics.v1.GetMonthlyNutritionInsightsResponse
	7,  // 17: analytics.v1.AnalyticsService.GetWeightProgressAnalysis:output_type -> analytics.v1.GetWeightProgressAnalysisResponse
	9,  // 18: analytics.v1.AnalyticsService.GetCalorieBalanceAnalysis:output_type -> analytics.v1.GetCalorieBalanceAnalysisResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
