// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

// 認証結果を表す型
type AuthResult struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int    `json:"expiresIn"`
	TokenType    string `json:"tokenType"`
	User         *User  `json:"user"`
}

// カロリーバランスを表す型
type CalorieBalance struct {
	// 開始日
	StartDate string `json:"startDate"`
	// 終了日
	EndDate string `json:"endDate"`
	// 総摂取カロリー
	TotalCaloriesIntake int `json:"totalCaloriesIntake"`
	// 総消費カロリー
	TotalCaloriesBurned int `json:"totalCaloriesBurned"`
	// 総カロリーバランス
	TotalCalorieBalance int `json:"totalCalorieBalance"`
	// 平均日次バランス
	AvgDailyBalance float64 `json:"avgDailyBalance"`
	// 赤字日数
	DaysInDeficit int `json:"daysInDeficit"`
	// 黒字日数
	DaysInSurplus int `json:"daysInSurplus"`
	// 赤字率(%)
	DeficitPercentage float64 `json:"deficitPercentage"`
	// 日次バランス
	DailyBalances []*DailyBalance `json:"dailyBalances"`
}

// 日次バランスを表す型
type DailyBalance struct {
	// 日付
	Date string `json:"date"`
	// 摂取カロリー
	CaloriesIntake int `json:"caloriesIntake"`
	// 消費カロリー
	CaloriesBurned int `json:"caloriesBurned"`
	// バランス
	Balance int `json:"balance"`
}

// 一日の栄養サマリーを表す型
type DailySummary struct {
	// 総摂取カロリー
	CaloriesIntake float64 `json:"caloriesIntake"`
	// 総消費カロリー
	CaloriesBurned float64 `json:"caloriesBurned"`
	// タンパク質摂取量
	Protein float64 `json:"protein"`
	// 炭水化物摂取量
	Carbohydrate float64 `json:"carbohydrate"`
	// 脂質摂取量
	Fat float64 `json:"fat"`
}

// 運動記録を表す型
type ExerciseLog struct {
	ID              string  `json:"id"`
	ExerciseName    string  `json:"exerciseName"`
	DurationMinutes int     `json:"durationMinutes"`
	CaloriesBurned  float64 `json:"caloriesBurned"`
	LoggedAt        string  `json:"loggedAt"`
}

// 内部データベースの食品を表す型
type Food struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Brand        *string `json:"brand,omitempty"`
	Calories     float64 `json:"calories"`
	Protein      float64 `json:"protein"`
	Carbohydrate float64 `json:"carbohydrate"`
	Fat          float64 `json:"fat"`
}

// 食事記録を表す型
type FoodLog struct {
	ID           string  `json:"id"`
	FoodName     string  `json:"foodName"`
	Quantity     float64 `json:"quantity"`
	Unit         string  `json:"unit"`
	Calories     float64 `json:"calories"`
	Protein      float64 `json:"protein"`
	Carbohydrate float64 `json:"carbohydrate"`
	Fat          float64 `json:"fat"`
	LoggedAt     string  `json:"loggedAt"`
}

// 運動記録用の入力型
type LogExerciseInput struct {
	// ユーザーが入力した運動名
	ExerciseName string `json:"exerciseName"`
	// 実施時間(分)
	DurationMinutes int `json:"durationMinutes"`
	// ユーザーが入力した消費カロリー
	CaloriesBurned float64 `json:"caloriesBurned"`
	// 実施日
	Date string `json:"date"`
}

// 食事記録用の入力型
type LogFoodInput struct {
	// foodsテーブルのID
	FoodID string `json:"foodId"`
	// 量
	Quantity float64 `json:"quantity"`
	// 単位 (例: g, 個)
	Unit string `json:"unit"`
	// 記録日
	Date string `json:"date"`
}

// 食事サマリーを表す型
type MealSummary struct {
	// 食事タイプ
	MealType string `json:"mealType"`
	// カロリー
	Calories int `json:"calories"`
	// タンパク質(g)
	Protein int `json:"protein"`
	// 炭水化物(g)
	Carbohydrate int `json:"carbohydrate"`
	// 脂質(g)
	Fat int `json:"fat"`
	// 食品リスト
	FoodItems []string `json:"foodItems"`
}

type Mutation struct {
}

// 月次栄養インサイトを表す型
type NutritionInsights struct {
	// 年
	Year string `json:"year"`
	// 月
	Month string `json:"month"`
	// 総カロリー
	TotalCalories int `json:"totalCalories"`
	// 平均日次カロリー
	AvgDailyCalories int `json:"avgDailyCalories"`
	// 総タンパク質
	TotalProtein int `json:"totalProtein"`
	// 平均日次タンパク質
	AvgDailyProtein int `json:"avgDailyProtein"`
	// 総炭水化物
	TotalCarbohydrate int `json:"totalCarbohydrate"`
	// 平均日次炭水化物
	AvgDailyCarbohydrate int `json:"avgDailyCarbohydrate"`
	// 総脂質
	TotalFat int `json:"totalFat"`
	// 平均日次脂質
	AvgDailyFat int `json:"avgDailyFat"`
	// よく食べた食品
	TopFoods []string `json:"topFoods"`
	// 推奨事項
	Recommendations []string `json:"recommendations"`
}

// 詳細な栄養サマリーを表す型
type NutritionSummary struct {
	// 日付
	Date string `json:"date"`
	// 総摂取カロリー
	CaloriesIntake int `json:"caloriesIntake"`
	// 総消費カロリー
	CaloriesBurned int `json:"caloriesBurned"`
	// カロリーバランス
	CaloriesBalance int `json:"caloriesBalance"`
	// タンパク質(g)
	Protein int `json:"protein"`
	// 炭水化物(g)
	Carbohydrate int `json:"carbohydrate"`
	// 脂質(g)
	Fat int `json:"fat"`
	// 食物繊維(g)
	Fiber int `json:"fiber"`
	// 糖質(g)
	Sugar int `json:"sugar"`
	// ナトリウム(mg)
	Sodium int `json:"sodium"`
	// 食事サマリー
	Meals []*MealSummary `json:"meals"`
}

// 栄養トレンドを表す型
type NutritionTrends struct {
	// 日次サマリー
	DailySummaries []*NutritionSummary `json:"dailySummaries"`
	// 平均カロリー
	CaloriesAvg float64 `json:"caloriesAvg"`
	// 平均タンパク質
	ProteinAvg float64 `json:"proteinAvg"`
	// 平均炭水化物
	CarbohydrateAvg float64 `json:"carbohydrateAvg"`
	// 平均脂質
	FatAvg float64 `json:"fatAvg"`
	// カロリートレンド(%)
	CaloriesTrend float64 `json:"caloriesTrend"`
	// タンパク質トレンド(%)
	ProteinTrend float64 `json:"proteinTrend"`
	// 炭水化物トレンド(%)
	CarbohydrateTrend float64 `json:"carbohydrateTrend"`
	// 脂質トレンド(%)
	FatTrend float64 `json:"fatTrend"`
}

type Query struct {
}

// ユーザー登録結果を表す型
type SignUpResult struct {
	UserID               string `json:"userId"`
	Email                string `json:"email"`
	ConfirmationRequired bool   `json:"confirmationRequired"`
	Message              string `json:"message"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

// 目標設定用の入力型
type UserGoalInput struct {
	TargetWeight float64 `json:"targetWeight"`
	TargetDate   string  `json:"targetDate"`
}

// プロフィール設定用の入力型
type UserProfileInput struct {
	Height        float64 `json:"height"`
	Weight        float64 `json:"weight"`
	ActivityLevel string  `json:"activityLevel"`
}

// 体重データポイントを表す型
type WeightDataPoint struct {
	// 日付
	Date string `json:"date"`
	// 体重
	Weight float64 `json:"weight"`
}

// 体重記録を表す型
type WeightLog struct {
	ID       string  `json:"id"`
	Weight   float64 `json:"weight"`
	LoggedAt string  `json:"loggedAt"`
}

// 体重進捗を表す型
type WeightProgress struct {
	// 開始日
	StartDate string `json:"startDate"`
	// 終了日
	EndDate string `json:"endDate"`
	// 開始体重
	StartWeight float64 `json:"startWeight"`
	// 終了体重
	EndWeight float64 `json:"endWeight"`
	// 体重変化
	WeightChange float64 `json:"weightChange"`
	// 体重変化率(%)
	WeightChangePercentage float64 `json:"weightChangePercentage"`
	// 平均週次変化
	AvgWeeklyChange float64 `json:"avgWeeklyChange"`
	// データポイント
	DataPoints []*WeightDataPoint `json:"dataPoints"`
	// トレンド
	Trend string `json:"trend"`
}
