// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/analytics/v1/analytics.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDailySummaryRequest represents a request for daily summary
type GetDailySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // Date in YYYY-MM-DD format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummaryRequest) Reset() {
	*x = GetDailySummaryRequest{}
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummaryRequest) ProtoMessage() {}

func (x *GetDailySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDailySummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetDailySummaryRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// GetDailySummaryResponse contains the daily summary data
type GetDailySummaryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CaloriesIntake float64                `protobuf:"fixed64,1,opt,name=calories_intake,json=caloriesIntake,proto3" json:"calories_intake,omitempty"` // Total calories consumed
	CaloriesBurned float64                `protobuf:"fixed64,2,opt,name=calories_burned,json=caloriesBurned,proto3" json:"calories_burned,omitempty"` // Total calories burned
	Protein        float64                `protobuf:"fixed64,3,opt,name=protein,proto3" json:"protein,omitempty"`                                     // Total protein consumed (grams)
	Carbohydrate   float64                `protobuf:"fixed64,4,opt,name=carbohydrate,proto3" json:"carbohydrate,omitempty"`                           // Total carbohydrate consumed (grams)
	Fat            float64                `protobuf:"fixed64,5,opt,name=fat,proto3" json:"fat,omitempty"`                                             // Total fat consumed (grams)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDailySummaryResponse) Reset() {
	*x = GetDailySummaryResponse{}
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummaryResponse) ProtoMessage() {}

func (x *GetDailySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummaryResponse.ProtoReflect.Descriptor instead.
func (*GetDailySummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetDailySummaryResponse) GetCaloriesIntake() float64 {
	if x != nil {
		return x.CaloriesIntake
	}
	return 0
}

func (x *GetDailySummaryResponse) GetCaloriesBurned() float64 {
	if x != nil {
		return x.CaloriesBurned
	}
	return 0
}

func (x *GetDailySummaryResponse) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *GetDailySummaryResponse) GetCarbohydrate() float64 {
	if x != nil {
		return x.Carbohydrate
	}
	return 0
}

func (x *GetDailySummaryResponse) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

var File_proto_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\"proto/analytics/v1/analytics.proto\x12\fanalytics.v1\",\n" +
	"\x16GetDailySummaryRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"\xbb\x01\n" +
	"\x17GetDailySummaryResponse\x12'\n" +
	"\x0fcalories_intake\x18\x01 \x01(\x01R\x0ecaloriesIntake\x12'\n" +
	"\x0fcalories_burned\x18\x02 \x01(\x01R\x0ecaloriesBurned\x12\x18\n" +
	"\aprotein\x18\x03 \x01(\x01R\aprotein\x12\"\n" +
	"\fcarbohydrate\x18\x04 \x01(\x01R\fcarbohydrate\x12\x10\n" +
	"\x03fat\x18\x05 \x01(\x01R\x03fat2r\n" +
	"\x10AnalyticsService\x12^\n" +
	"\x0fGetDailySummary\x12$.analytics.v1.GetDailySummaryRequest\x1a%.analytics.v1.GetDailySummaryResponseBJZHgithub.com/HirotakaUchishiba/calomeal_mvp/proto/analytics/v1;analyticspbb\x06proto3"

var (
	file_proto_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_v1_analytics_proto_rawDescData []byte
)

func file_proto_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_v1_analytics_proto_rawDesc), len(file_proto_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_v1_analytics_proto_rawDescData
}

var file_proto_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_analytics_v1_analytics_proto_goTypes = []any{
	(*GetDailySummaryRequest)(nil),  // 0: analytics.v1.GetDailySummaryRequest
	(*GetDailySummaryResponse)(nil), // 1: analytics.v1.GetDailySummaryResponse
}
var file_proto_analytics_v1_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.v1.AnalyticsService.GetDailySummary:input_type -> analytics.v1.GetDailySummaryRequest
	1, // 1: analytics.v1.AnalyticsService.GetDailySummary:output_type -> analytics.v1.GetDailySummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analytics_v1_analytics_proto_init() }
func file_proto_analytics_v1_analytics_proto_init() {
	if File_proto_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_v1_analytics_proto_rawDesc), len(file_proto_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_v1_analytics_proto = out.File
	file_proto_analytics_v1_analytics_proto_goTypes = nil
	file_proto_analytics_v1_analytics_proto_depIdxs = nil
}
