// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/foods/v1/foods.proto

package foodspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchFoodsRequest represents a food search request
type SearchFoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`  // Search keyword
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Maximum number of results (default: 20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFoodsRequest) Reset() {
	*x = SearchFoodsRequest{}
	mi := &file_proto_foods_v1_foods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoodsRequest) ProtoMessage() {}

func (x *SearchFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foods_v1_foods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoodsRequest.ProtoReflect.Descriptor instead.
func (*SearchFoodsRequest) Descriptor() ([]byte, []int) {
	return file_proto_foods_v1_foods_proto_rawDescGZIP(), []int{0}
}

func (x *SearchFoodsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchFoodsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchFoodsResponse contains the search results
type SearchFoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foods         []*Food                `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty"` // List of matching foods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFoodsResponse) Reset() {
	*x = SearchFoodsResponse{}
	mi := &file_proto_foods_v1_foods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoodsResponse) ProtoMessage() {}

func (x *SearchFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foods_v1_foods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoodsResponse.ProtoReflect.Descriptor instead.
func (*SearchFoodsResponse) Descriptor() ([]byte, []int) {
	return file_proto_foods_v1_foods_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFoodsResponse) GetFoods() []*Food {
	if x != nil {
		return x.Foods
	}
	return nil
}

// GetFoodByIdRequest represents a request to get food by ID
type GetFoodByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"` // Food ID to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodByIdRequest) Reset() {
	*x = GetFoodByIdRequest{}
	mi := &file_proto_foods_v1_foods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodByIdRequest) ProtoMessage() {}

func (x *GetFoodByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foods_v1_foods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodByIdRequest.ProtoReflect.Descriptor instead.
func (*GetFoodByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_foods_v1_foods_proto_rawDescGZIP(), []int{2}
}

func (x *GetFoodByIdRequest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

// GetFoodByIdResponse contains the requested food
type GetFoodByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          *Food                  `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"` // The requested food
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodByIdResponse) Reset() {
	*x = GetFoodByIdResponse{}
	mi := &file_proto_foods_v1_foods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodByIdResponse) ProtoMessage() {}

func (x *GetFoodByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foods_v1_foods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodByIdResponse.ProtoReflect.Descriptor instead.
func (*GetFoodByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_foods_v1_foods_proto_rawDescGZIP(), []int{3}
}

func (x *GetFoodByIdResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

// Food represents a food item with nutritional information
type Food struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // Unique food identifier
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                   // Food name
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`                 // Brand name (optional)
	Calories      float64                `protobuf:"fixed64,4,opt,name=calories,proto3" json:"calories,omitempty"`         // Calories per 100g
	Protein       float64                `protobuf:"fixed64,5,opt,name=protein,proto3" json:"protein,omitempty"`           // Protein per 100g (grams)
	Carbohydrate  float64                `protobuf:"fixed64,6,opt,name=carbohydrate,proto3" json:"carbohydrate,omitempty"` // Carbohydrate per 100g (grams)
	Fat           float64                `protobuf:"fixed64,7,opt,name=fat,proto3" json:"fat,omitempty"`                   // Fat per 100g (grams)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Food) Reset() {
	*x = Food{}
	mi := &file_proto_foods_v1_foods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foods_v1_foods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_proto_foods_v1_foods_proto_rawDescGZIP(), []int{4}
}

func (x *Food) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Food) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Food) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Food) GetCalories() float64 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *Food) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *Food) GetCarbohydrate() float64 {
	if x != nil {
		return x.Carbohydrate
	}
	return 0
}

func (x *Food) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

var File_proto_foods_v1_foods_proto protoreflect.FileDescriptor

const file_proto_foods_v1_foods_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/foods/v1/foods.proto\x12\bfoods.v1\"@\n" +
	"\x12SearchFoodsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\";\n" +
	"\x13SearchFoodsResponse\x12$\n" +
	"\x05foods\x18\x01 \x03(\v2\x0e.foods.v1.FoodR\x05foods\"-\n" +
	"\x12GetFoodByIdRequest\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\"9\n" +
	"\x13GetFoodByIdResponse\x12\"\n" +
	"\x04food\x18\x01 \x01(\v2\x0e.foods.v1.FoodR\x04food\"\xac\x01\n" +
	"\x04Food\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x1a\n" +
	"\bcalories\x18\x04 \x01(\x01R\bcalories\x12\x18\n" +
	"\aprotein\x18\x05 \x01(\x01R\aprotein\x12\"\n" +
	"\fcarbohydrate\x18\x06 \x01(\x01R\fcarbohydrate\x12\x10\n" +
	"\x03fat\x18\a \x01(\x01R\x03fat2\xa5\x01\n" +
	"\vFoodService\x12J\n" +
	"\vSearchFoods\x12\x1c.foods.v1.SearchFoodsRequest\x1a\x1d.foods.v1.SearchFoodsResponse\x12J\n" +
	"\vGetFoodById\x12\x1c.foods.v1.GetFoodByIdRequest\x1a\x1d.foods.v1.GetFoodByIdResponseBBZ@github.com/HirotakaUchishiba/calomeal_mvp/proto/foods/v1;foodspbb\x06proto3"

var (
	file_proto_foods_v1_foods_proto_rawDescOnce sync.Once
	file_proto_foods_v1_foods_proto_rawDescData []byte
)

func file_proto_foods_v1_foods_proto_rawDescGZIP() []byte {
	file_proto_foods_v1_foods_proto_rawDescOnce.Do(func() {
		file_proto_foods_v1_foods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_foods_v1_foods_proto_rawDesc), len(file_proto_foods_v1_foods_proto_rawDesc)))
	})
	return file_proto_foods_v1_foods_proto_rawDescData
}

var file_proto_foods_v1_foods_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_foods_v1_foods_proto_goTypes = []any{
	(*SearchFoodsRequest)(nil),  // 0: foods.v1.SearchFoodsRequest
	(*SearchFoodsResponse)(nil), // 1: foods.v1.SearchFoodsResponse
	(*GetFoodByIdRequest)(nil),  // 2: foods.v1.GetFoodByIdRequest
	(*GetFoodByIdResponse)(nil), // 3: foods.v1.GetFoodByIdResponse
	(*Food)(nil),                // 4: foods.v1.Food
}
var file_proto_foods_v1_foods_proto_depIdxs = []int32{
	4, // 0: foods.v1.SearchFoodsResponse.foods:type_name -> foods.v1.Food
	4, // 1: foods.v1.GetFoodByIdResponse.food:type_name -> foods.v1.Food
	0, // 2: foods.v1.FoodService.SearchFoods:input_type -> foods.v1.SearchFoodsRequest
	2, // 3: foods.v1.FoodService.GetFoodById:input_type -> foods.v1.GetFoodByIdRequest
	1, // 4: foods.v1.FoodService.SearchFoods:output_type -> foods.v1.SearchFoodsResponse
	3, // 5: foods.v1.FoodService.GetFoodById:output_type -> foods.v1.GetFoodByIdResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_foods_v1_foods_proto_init() }
func file_proto_foods_v1_foods_proto_init() {
	if File_proto_foods_v1_foods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_foods_v1_foods_proto_rawDesc), len(file_proto_foods_v1_foods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_foods_v1_foods_proto_goTypes,
		DependencyIndexes: file_proto_foods_v1_foods_proto_depIdxs,
		MessageInfos:      file_proto_foods_v1_foods_proto_msgTypes,
	}.Build()
	File_proto_foods_v1_foods_proto = out.File
	file_proto_foods_v1_foods_proto_goTypes = nil
	file_proto_foods_v1_foods_proto_depIdxs = nil
}
