// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: analytics/v1/analytics.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetDailyNutritionSummary_FullMethodName    = "/analytics.v1.AnalyticsService/GetDailyNutritionSummary"
	AnalyticsService_GetWeeklyNutritionTrends_FullMethodName    = "/analytics.v1.AnalyticsService/GetWeeklyNutritionTrends"
	AnalyticsService_GetMonthlyNutritionInsights_FullMethodName = "/analytics.v1.AnalyticsService/GetMonthlyNutritionInsights"
	AnalyticsService_GetWeightProgressAnalysis_FullMethodName   = "/analytics.v1.AnalyticsService/GetWeightProgressAnalysis"
	AnalyticsService_GetCalorieBalanceAnalysis_FullMethodName   = "/analytics.v1.AnalyticsService/GetCalorieBalanceAnalysis"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analytics service provides data analysis and insights
type AnalyticsServiceClient interface {
	// Get daily nutrition summary
	GetDailyNutritionSummary(ctx context.Context, in *GetDailyNutritionSummaryRequest, opts ...grpc.CallOption) (*GetDailyNutritionSummaryResponse, error)
	// Get weekly nutrition trends
	GetWeeklyNutritionTrends(ctx context.Context, in *GetWeeklyNutritionTrendsRequest, opts ...grpc.CallOption) (*GetWeeklyNutritionTrendsResponse, error)
	// Get monthly nutrition insights
	GetMonthlyNutritionInsights(ctx context.Context, in *GetMonthlyNutritionInsightsRequest, opts ...grpc.CallOption) (*GetMonthlyNutritionInsightsResponse, error)
	// Get weight progress analysis
	GetWeightProgressAnalysis(ctx context.Context, in *GetWeightProgressAnalysisRequest, opts ...grpc.CallOption) (*GetWeightProgressAnalysisResponse, error)
	// Get calorie balance analysis
	GetCalorieBalanceAnalysis(ctx context.Context, in *GetCalorieBalanceAnalysisRequest, opts ...grpc.CallOption) (*GetCalorieBalanceAnalysisResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetDailyNutritionSummary(ctx context.Context, in *GetDailyNutritionSummaryRequest, opts ...grpc.CallOption) (*GetDailyNutritionSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyNutritionSummaryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDailyNutritionSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetWeeklyNutritionTrends(ctx context.Context, in *GetWeeklyNutritionTrendsRequest, opts ...grpc.CallOption) (*GetWeeklyNutritionTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeeklyNutritionTrendsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetWeeklyNutritionTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMonthlyNutritionInsights(ctx context.Context, in *GetMonthlyNutritionInsightsRequest, opts ...grpc.CallOption) (*GetMonthlyNutritionInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlyNutritionInsightsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMonthlyNutritionInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetWeightProgressAnalysis(ctx context.Context, in *GetWeightProgressAnalysisRequest, opts ...grpc.CallOption) (*GetWeightProgressAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeightProgressAnalysisResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetWeightProgressAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetCalorieBalanceAnalysis(ctx context.Context, in *GetCalorieBalanceAnalysisRequest, opts ...grpc.CallOption) (*GetCalorieBalanceAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCalorieBalanceAnalysisResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCalorieBalanceAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// Analytics service provides data analysis and insights
type AnalyticsServiceServer interface {
	// Get daily nutrition summary
	GetDailyNutritionSummary(context.Context, *GetDailyNutritionSummaryRequest) (*GetDailyNutritionSummaryResponse, error)
	// Get weekly nutrition trends
	GetWeeklyNutritionTrends(context.Context, *GetWeeklyNutritionTrendsRequest) (*GetWeeklyNutritionTrendsResponse, error)
	// Get monthly nutrition insights
	GetMonthlyNutritionInsights(context.Context, *GetMonthlyNutritionInsightsRequest) (*GetMonthlyNutritionInsightsResponse, error)
	// Get weight progress analysis
	GetWeightProgressAnalysis(context.Context, *GetWeightProgressAnalysisRequest) (*GetWeightProgressAnalysisResponse, error)
	// Get calorie balance analysis
	GetCalorieBalanceAnalysis(context.Context, *GetCalorieBalanceAnalysisRequest) (*GetCalorieBalanceAnalysisResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetDailyNutritionSummary(context.Context, *GetDailyNutritionSummaryRequest) (*GetDailyNutritionSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyNutritionSummary not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetWeeklyNutritionTrends(context.Context, *GetWeeklyNutritionTrendsRequest) (*GetWeeklyNutritionTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeeklyNutritionTrends not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMonthlyNutritionInsights(context.Context, *GetMonthlyNutritionInsightsRequest) (*GetMonthlyNutritionInsightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyNutritionInsights not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetWeightProgressAnalysis(context.Context, *GetWeightProgressAnalysisRequest) (*GetWeightProgressAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeightProgressAnalysis not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCalorieBalanceAnalysis(context.Context, *GetCalorieBalanceAnalysisRequest) (*GetCalorieBalanceAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCalorieBalanceAnalysis not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetDailyNutritionSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyNutritionSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDailyNutritionSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDailyNutritionSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDailyNutritionSummary(ctx, req.(*GetDailyNutritionSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetWeeklyNutritionTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyNutritionTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetWeeklyNutritionTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetWeeklyNutritionTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetWeeklyNutritionTrends(ctx, req.(*GetWeeklyNutritionTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMonthlyNutritionInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyNutritionInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMonthlyNutritionInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMonthlyNutritionInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMonthlyNutritionInsights(ctx, req.(*GetMonthlyNutritionInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetWeightProgressAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeightProgressAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetWeightProgressAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetWeightProgressAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetWeightProgressAnalysis(ctx, req.(*GetWeightProgressAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetCalorieBalanceAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCalorieBalanceAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCalorieBalanceAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCalorieBalanceAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCalorieBalanceAnalysis(ctx, req.(*GetCalorieBalanceAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyNutritionSummary",
			Handler:    _AnalyticsService_GetDailyNutritionSummary_Handler,
		},
		{
			MethodName: "GetWeeklyNutritionTrends",
			Handler:    _AnalyticsService_GetWeeklyNutritionTrends_Handler,
		},
		{
			MethodName: "GetMonthlyNutritionInsights",
			Handler:    _AnalyticsService_GetMonthlyNutritionInsights_Handler,
		},
		{
			MethodName: "GetWeightProgressAnalysis",
			Handler:    _AnalyticsService_GetWeightProgressAnalysis_Handler,
		},
		{
			MethodName: "GetCalorieBalanceAnalysis",
			Handler:    _AnalyticsService_GetCalorieBalanceAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
