package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/HirotakaUchishiba/calomeal_mvp/backend"
	"github.com/HirotakaUchishiba/calomeal_mvp/backend/internal/service/log"
)

// CompleteOnboarding is the resolver for the completeOnboarding field.
func (r *mutationResolver) CompleteOnboarding(ctx context.Context, profile backend.UserProfileInput, goal backend.UserGoalInput) (*backend.User, error) {
	// ステップ2で接続したUserServiceのメソッドを呼び出す
	err := r.Resolver.UserService.CompleteOnboarding(ctx)
	if err != nil {
		// TODO: エラーハンドリングを実装
		return nil, err
	}

	// 現時点ではダミーのユーザー情報を返す
	dummyUser := &backend.User{
		ID:    "dummy-user-id",
		Email: "dummy@example.com",
	}

	return dummyUser, nil
}

// LogFood is the resolver for the logFood field.
func (r *mutationResolver) LogFood(ctx context.Context, input backend.LogFoodInput) (*backend.FoodLog, error) {
	// TODO: コンテキストから実際のユーザーIDを取得
	userID := "550e8400-e29b-41d4-a716-446655440000" // 有効なUUID形式のダミー値

	// foodIdから食品情報を取得（TODO: 実際の食品データベースから取得）
	// 現時点ではダミーデータを使用
	foodName := "選択された食品"
	caloriesPerUnit := 100.0
	proteinPerUnit := 10.0
	carbohydratePerUnit := 20.0
	fatPerUnit := 5.0

	// 栄養素を計算（量 × 単位あたりの栄養素）
	calories := input.Quantity * caloriesPerUnit
	protein := input.Quantity * proteinPerUnit
	carbohydrate := input.Quantity * carbohydratePerUnit
	fat := input.Quantity * fatPerUnit

	// 入力型をサービス層の型に変換
	serviceInput := log.LogFoodInput{
		FoodName:     foodName,
		Quantity:     input.Quantity,
		Unit:         input.Unit,
		Calories:     calories,
		Protein:      protein,
		Carbohydrate: carbohydrate,
		Fat:          fat,
		Date:         input.Date,
	}

	// LogServiceを呼び出す
	logID, err := r.Resolver.LogService.LogFood(ctx, userID, serviceInput)
	if err != nil {
		return nil, err
	}

	// 成功レスポンスを返す
	return &backend.FoodLog{
		ID:           fmt.Sprintf("%d", logID),
		FoodName:     foodName,
		Quantity:     input.Quantity,
		Unit:         input.Unit,
		Calories:     calories,
		Protein:      protein,
		Carbohydrate: carbohydrate,
		Fat:          fat,
		LoggedAt:     input.Date,
	}, nil
}

// LogExercise is the resolver for the logExercise field.
func (r *mutationResolver) LogExercise(ctx context.Context, input backend.LogExerciseInput) (*backend.ExerciseLog, error) {
	// TODO: コンテキストから実際のユーザーIDを取得
	userID := "550e8400-e29b-41d4-a716-446655440000" // 有効なUUID形式のダミー値

	// 入力型をサービス層の型に変換
	serviceInput := log.LogExerciseInput{
		ExerciseName:    input.ExerciseName,
		DurationMinutes: input.DurationMinutes,
		CaloriesBurned:  input.CaloriesBurned,
		Date:            input.Date,
	}

	// LogServiceを呼び出す
	logID, err := r.Resolver.LogService.LogExercise(ctx, userID, serviceInput)
	if err != nil {
		return nil, err
	}

	// 成功レスポンスを返す (ダミーデータ)
	return &backend.ExerciseLog{
		ID:              fmt.Sprintf("%d", logID),
		ExerciseName:    input.ExerciseName,
		DurationMinutes: input.DurationMinutes,
		CaloriesBurned:  input.CaloriesBurned,
		LoggedAt:        input.Date,
	}, nil
}

// SearchFood is the resolver for the searchFood field.
func (r *queryResolver) SearchFood(ctx context.Context, query string) ([]*backend.Food, error) {
	// FoodDataServiceを呼び出す
	results, err := r.Resolver.FoodDataService.SearchFood(ctx, query)
	if err != nil {
		return nil, err
	}

	// サービス層の型 (fooddata.Food) からGraphQLの型 (*backend.Food) へ変換
	foods := make([]*backend.Food, 0, len(results))
	for _, res := range results {
		foods = append(foods, &backend.Food{
			ID:           fmt.Sprintf("%d", res.ID),
			Name:         res.Name,
			Brand:        res.Brand,
			Calories:     res.Calories,
			Protein:      res.Protein,
			Carbohydrate: res.Carbohydrate,
			Fat:          res.Fat,
		})
	}
	return foods, nil
}

// DailySummary is the resolver for the dailySummary field.
func (r *queryResolver) DailySummary(ctx context.Context, date string) (*backend.DailySummary, error) {
    // TODO: コンテキストから実際のユーザーIDを取得
    userID := "550e8400-e29b-41d4-a716-446655440000"

    // LogServiceから日次サマリーを取得
    summary, err := r.Resolver.LogService.GetDailySummary(ctx, userID, date)
    if err != nil {
        return nil, err
    }

    // サービス層の型からGraphQLの型に変換
    return &backend.DailySummary{
        CaloriesIntake: summary.CaloriesIntake,
        CaloriesBurned: summary.CaloriesBurned,
        Protein:        summary.Protein,
        Carbohydrate:   summary.Carbohydrate,
        Fat:            summary.Fat,
    }, nil
}

// Mutation returns backend.MutationResolver implementation.
func (r *Resolver) Mutation() backend.MutationResolver { return &mutationResolver{r} }

// Query returns backend.QueryResolver implementation.
func (r *Resolver) Query() backend.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
