package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/HirotakaUchishiba/calomeal_mvp/backend"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, email string, password string) (*backend.SignUpResult, error) {
	panic(fmt.Errorf("not implemented: SignUp - signUp"))
}

// ConfirmSignUp is the resolver for the confirmSignUp field.
func (r *mutationResolver) ConfirmSignUp(ctx context.Context, email string, confirmationCode string) (bool, error) {
	panic(fmt.Errorf("not implemented: ConfirmSignUp - confirmSignUp"))
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, email string, password string) (*backend.AuthResult, error) {
	panic(fmt.Errorf("not implemented: SignIn - signIn"))
}

// SignOut is the resolver for the signOut field.
func (r *mutationResolver) SignOut(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: SignOut - signOut"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*backend.AuthResult, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, email string) (bool, error) {
	panic(fmt.Errorf("not implemented: ResetPassword - resetPassword"))
}

// ConfirmResetPassword is the resolver for the confirmResetPassword field.
func (r *mutationResolver) ConfirmResetPassword(ctx context.Context, email string, confirmationCode string, newPassword string) (bool, error) {
	panic(fmt.Errorf("not implemented: ConfirmResetPassword - confirmResetPassword"))
}

// CompleteOnboarding is the resolver for the completeOnboarding field.
func (r *mutationResolver) CompleteOnboarding(ctx context.Context, profile backend.UserProfileInput, goal backend.UserGoalInput) (*backend.User, error) {
	panic(fmt.Errorf("not implemented: CompleteOnboarding - completeOnboarding"))
}

// LogFood is the resolver for the logFood field.
func (r *mutationResolver) LogFood(ctx context.Context, input backend.LogFoodInput) (*backend.FoodLog, error) {
	panic(fmt.Errorf("not implemented: LogFood - logFood"))
}

// LogExercise is the resolver for the logExercise field.
func (r *mutationResolver) LogExercise(ctx context.Context, input backend.LogExerciseInput) (*backend.ExerciseLog, error) {
	panic(fmt.Errorf("not implemented: LogExercise - logExercise"))
}

// LogWeight is the resolver for the logWeight field.
func (r *mutationResolver) LogWeight(ctx context.Context, weight float64, date string) (*backend.WeightLog, error) {
	panic(fmt.Errorf("not implemented: LogWeight - logWeight"))
}

// SearchFood is the resolver for the searchFood field.
func (r *queryResolver) SearchFood(ctx context.Context, query string) ([]*backend.Food, error) {
	panic(fmt.Errorf("not implemented: SearchFood - searchFood"))
}

// GetFoodByID is the resolver for the getFoodById field.
func (r *queryResolver) GetFoodByID(ctx context.Context, foodID string) (*backend.Food, error) {
	panic(fmt.Errorf("not implemented: GetFoodByID - getFoodById"))
}

// DailySummary is the resolver for the dailySummary field.
func (r *queryResolver) DailySummary(ctx context.Context, date string) (*backend.DailySummary, error) {
	panic(fmt.Errorf("not implemented: DailySummary - dailySummary"))
}

// FoodLogs is the resolver for the foodLogs field.
func (r *queryResolver) FoodLogs(ctx context.Context, date string) ([]*backend.FoodLog, error) {
	panic(fmt.Errorf("not implemented: FoodLogs - foodLogs"))
}

// ExerciseLogs is the resolver for the exerciseLogs field.
func (r *queryResolver) ExerciseLogs(ctx context.Context, date string) ([]*backend.ExerciseLog, error) {
	panic(fmt.Errorf("not implemented: ExerciseLogs - exerciseLogs"))
}

// WeightLogs is the resolver for the weightLogs field.
func (r *queryResolver) WeightLogs(ctx context.Context, date string) ([]*backend.WeightLog, error) {
	panic(fmt.Errorf("not implemented: WeightLogs - weightLogs"))
}

// NutritionSummary is the resolver for the nutritionSummary field.
func (r *queryResolver) NutritionSummary(ctx context.Context, date string) (*backend.NutritionSummary, error) {
	panic(fmt.Errorf("not implemented: NutritionSummary - nutritionSummary"))
}

// NutritionTrends is the resolver for the nutritionTrends field.
func (r *queryResolver) NutritionTrends(ctx context.Context, startDate string, endDate string) (*backend.NutritionTrends, error) {
	panic(fmt.Errorf("not implemented: NutritionTrends - nutritionTrends"))
}

// NutritionInsights is the resolver for the nutritionInsights field.
func (r *queryResolver) NutritionInsights(ctx context.Context, year string, month string) (*backend.NutritionInsights, error) {
	panic(fmt.Errorf("not implemented: NutritionInsights - nutritionInsights"))
}

// WeightProgress is the resolver for the weightProgress field.
func (r *queryResolver) WeightProgress(ctx context.Context, startDate string, endDate string) (*backend.WeightProgress, error) {
	panic(fmt.Errorf("not implemented: WeightProgress - weightProgress"))
}

// CalorieBalance is the resolver for the calorieBalance field.
func (r *queryResolver) CalorieBalance(ctx context.Context, startDate string, endDate string) (*backend.CalorieBalance, error) {
	panic(fmt.Errorf("not implemented: CalorieBalance - calorieBalance"))
}

// Mutation returns backend.MutationResolver implementation.
func (r *Resolver) Mutation() backend.MutationResolver { return &mutationResolver{r} }

// Query returns backend.QueryResolver implementation.
func (r *Resolver) Query() backend.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
